# 本番環境用ネームスペース
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    environment: production
---
# 本番環境用ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  # Kafka設定
  KAFKA_BROKER: "my-cluster-kafka-bootstrap.production.svc.cluster.local:9092"
  
  # ログレベル
  LOG_LEVEL: "warn"
  
  # 機能フラグ
  ENABLE_METRICS: "true"
  ENABLE_DISTRIBUTED_TRACING: "true"
  ENABLE_CORS: "false"
  
  # フロントエンド設定
  NEXT_PUBLIC_ENVIRONMENT: "production"
  NEXT_PUBLIC_API_BASE_URL: "https://api.your-domain.com"
  NEXT_PUBLIC_WS_URL: "wss://api.your-domain.com"
---
# 本番環境用Secret（機密情報）
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  # Base64エンコードされた値を設定
  # echo -n "your-secret" | base64
  DATABASE_PASSWORD: eW91ci1kYXRhYmFzZS1wYXNzd29yZA==
  JWT_SECRET: eW91ci1qd3Qtc2VjcmV0
  API_KEY: eW91ci1hcGkta2V5
---
# NetworkPolicy（本番環境用セキュリティ）
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-network-policy
  namespace: production
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector: {}
  egress:
  - {}  # 外部への通信を許可（必要に応じて制限）
---
# リソースクォータ
apiVersion: v1
kind: ResourceQuota
metadata:
  name: production-quota
  namespace: production
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    pods: "50"
    services: "20"
---
# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: production
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
